SENEC_SECTION_BAT1 = "BAT1"
SENEC_SECTION_BAT1OBJ1 = "BAT1OBJ1"
SENEC_SECTION_BMS = "BMS"
SENEC_SECTION_BMS_PARA = "BMS_PARA"
SENEC_SECTION_CASC = "CASC"
SENEC_SECTION_DEBUG = "DEBUG"
SENEC_SECTION_DISPLAY = "DISPLAY"
SENEC_SECTION_ENERGY = "ENERGY"
SENEC_SECTION_FACTORY = "FACTORY"
SENEC_SECTION_FEATURES = "FEATURES"
SENEC_SECTION_FILE = "FILE"
SENEC_SECTION_GRIDCONFIG = "GRIDCONFIG"
SENEC_SECTION_LOG = "LOG"
SENEC_SECTION_PM1 = "PM1"
SENEC_SECTION_PM1OBJ1 = "PM1OBJ1"
SENEC_SECTION_PM1OBJ2 = "PM1OBJ2"
SENEC_SECTION_PV1 = "PV1"
SENEC_SECTION_PWR_UNIT = "PWR_UNIT"
SENEC_SECTION_RTC = "RTC"
SENEC_SECTION_SELFTEST_RESULTS = "SELFTEST_RESULTS"
SENEC_SECTION_SOCKETS = "SOCKETS"
SENEC_SECTION_STATISTIC = "STATISTIC"
SENEC_SECTION_STECA = "STECA"
SENEC_SECTION_SYS_UPDATE = "SYS_UPDATE"
SENEC_SECTION_TEMPMEASURE = "TEMPMEASURE"
SENEC_SECTION_TEST = "TEST"
SENEC_SECTION_UPDATE = "UPDATE"
SENEC_SECTION_WALLBOX = "WALLBOX"
SENEC_SECTION_WIZARD = "WIZARD"
SENEC_SECTION_CURRENT_IMBALANCE_CONTROL = "CURRENT_IMBALANCE_CONTROL"
SENEC_SECTION_BMZ_CURRENT_LIMITS = "BMZ_CURRENT_LIMITS"
SENEC_SECTION_CELL_DEVIATION_ROC = "CELL_DEVIATION_ROC"
SENEC_SECTION_SENEC_IO_INPUT = "SENEC_IO_INPUT"
SENEC_SECTION_SENEC_IO_OUTPUT = "SENEC_IO_OUTPUT"
SENEC_SECTION_IPU = "IPU"
SENEC_SECTION_FAN_TEST = "FAN_TEST"
SENEC_SECTION_FAN_SPEED = "FAN_SPEED"

BATT_TYPE_NAME = {
    0: "Studer Xtender",
    1: "SenecBatt",
    2: "Senec Inverter V2",
    3: "SENEC.Inverter V2.1",
    4: "SENEC.Inverter V3 LV"
};

SYSTEM_TYPE_NAME = {
    0: "Senec Home 8.0 / Blei",
    1: "Senec Business 30.0 / Blei",
    2: "Solarinvert Storage 10.0 / Blei",
    3: "Senec Home 4.0 / Blei",
    4: "Senec Home 5.0/7.5/10.0 / Lithium",
    5: "Senec Home 15.0 / Lithium",
    6: "Senec Business 25.0 / Lithium",
    7: "Senec Home 6.0 Pb",
    8: "Senec Home 10.0 Pb",
    9: "Senec Home V2 5.0/7.5/10.0",
    10: "Senec Business V2 30.0 / Blei",
    11: "Senec Home V2 10.0 / Blei",
    12: "OEM LG",
    13: "Senec Business V2_2ph / Lithium",
    14: "Senec Business V2 3ph / Lithium",
    15: "Senec Home V2.1 1ph / Lithium",
    16: "ADS Tec",
    17: "SENEC.Home V3 hybrid",
    18: "SENEC.Home V3 hybrid duo",
    19: "SENEC.Home V3 hybrid",
};

SYSTEM_STATE_NAME = {
    0: "INITIALSTATE",
    1: "ERROR INVERTER COMMUNICATION",
    2: "ERROR ELECTRICY METER",
    3: "RIPPLE CONTROL RECEIVER",
    4: "INITIAL CHARGE",
    5: "MAINTENANCE CHARGE",
    6: "MAINTENANCE READY",
    7: "MAINTENANCE REQUIRED",
    8: "MAN. SAFETY CHARGE",
    9: "SAFETY CHARGE READY",
    10: "FULL CHARGE",
    11: "EQUALIZATION: CHARGE",
    12: "DESULFATATION: CHARGE",
    13: "BATTERY FULL",
    14: "CHARGE",
    15: "BATTERY EMPTY",
    16: "DISCHARGE",
    17: "PV + DISCHARGE",
    18: "GRID + DISCHARGE",
    19: "PASSIVE",
    20: "OFF",
    21: "OWN CONSUMPTION",
    22: "RESTART",
    23: "MAN. EQUALIZATION: CHARGE",
    24: "MAN. DESULFATATION: CHARGE",
    25: "SAFETY CHARGE",
    26: "BATTERY PROTECTION MODE",
    27: "EG ERROR",
    28: "EG CHARGE",
    29: "EG DISCHARGE",
    30: "EG PASSIVE",
    31: "EG PROHIBIT CHARGE",
    32: "EG PROHIBIT DISCHARGE",
    33: "EMERGENCY CHARGE",
    34: "SOFTWARE UPDATE",
    35: "NSP ERROR",
    36: "NSP ERROR: GRID",
    37: "NSP ERROR: HARDWRE",
    38: "NO SERVER CONNECTION",
    39: "BMS ERROR",
    40: "MAINTENANCE: FILTER",
    41: "BMS SHUTDOWN",
    42: "WAITING EXCESS",
    43: "CAPACITY TEST: CHARGE",
    44: "CAPACITY TEST: DISCHARGE",
    45: "MAN. DESULFATATION: WAIT",
    46: "MAN. DESULFATATION: READY",
    47: "MAN. DESULFATATION: ERROR",
    48: "EQUALIZATION: WAIT",
    49: "EMERGENCY CHARGE: ERROR",
    50: "MAN. EQUALIZATION: WAIT",
    51: "MAN. EQUALIZATION: ERROR",
    52: "MAN: EQUALIZATION: READY",
    53: "AUTO. DESULFATATION: WAIT",
    54: "ABSORPTION PHASE",
    55: "DC-SWITCH OFF",
    56: "PEAK-SHAVING: WAIT",
    57: "ERROR BATTERY INVERTER",
    58: "NPU-ERROR",
    59: "BMS OFFLINE",
    60: "MAINTENANCE CHARGE ERROR",
    61: "MAN. SAFETY CHARGE ERROR",
    62: "SAFETY CHARGE ERROR",
    63: "NO CONNECTION TO MASTER",
    64: "LITHIUM SAFE MODE ACTIVE",
    65: "LITHIUM SAFE MODE DONE",
    66: "BATTERY VOLTAGE ERROR",
    67: "BMS DC SWITCHED OFF",
    68: "GRID INITIALIZATION",
    69: "GRID STABILIZATION",
    70: "REMOTE SHUTDOWN",
    71: "OFFPEAK-CHARGE",
    72: "ERROR HALFBRIDGE",
    73: "BMS: ERROR OPERATING TEMPERATURE",
    74: "FACTORY SETTINGS NOT FOUND",
    75: "BACKUP POWER MODE - ACTIVE",
    76: "BACKUP POWER MODE - BATTERY EMPTY",
    77: "BACKUP POWER MODE ERROR",
    78: "INITIALISING",
    79: "INSTALLATION MODE",
    80: "GRID OFFLINE",
    81: "BMS UPDATE NEEDED",
    82: "BMS CONFIGURATION NEEDED",
    83: "INSULATION TEST",
    84: "SELFTEST",
    85: "EXTERNAL CONTROL",
    86: "ERROR: TEMPERATURESENSOR",
    87: "GRID OPERATOR: CHARGE PROHIBITED",
    88: "GRID OPERATOR: DISCHARGE PROHIBITED",
    89: "SPARE CAPACITY",
    90: "SELFTEST ERROR",
    91: "EARTH FAULT",
    92: "PV-MODE",
    93: "REMOTE DISCONNECTION",
    94: "ERROR DRM0",
    95: "BATTERY DIAGNOSIS",
    96: "BALANCING",
    97: "SAFETY DISCHARGE",
    98: "BMS ERROR - MODULE IMBALANCE"
}
