"""Constants for the Senec integration."""
from typing import Final
from dataclasses import dataclass

from homeassistant.components.binary_sensor import BinarySensorEntityDescription
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.components.switch import SwitchEntityDescription
from homeassistant.components.number import (
    NumberEntityDescription,
    NumberDeviceClass, NumberMode
)
from homeassistant.const import (
    ENERGY_KILO_WATT_HOUR,
    PERCENTAGE,
    POWER_WATT,
    POWER_KILO_WATT,
    TEMP_CELSIUS,
    UnitOfElectricPotential,
    UnitOfElectricCurrent, UnitOfFrequency,
)
from homeassistant.helpers.entity import EntityCategory

from custom_components.senec.pysenec_ha.constants import (
    SENEC_SECTION_BMS,
    SENEC_SECTION_ENERGY,
    SENEC_SECTION_FAN_SPEED,
    SENEC_SECTION_STATISTIC,
    SENEC_SECTION_PM1OBJ1,
    SENEC_SECTION_PM1OBJ2,
    SENEC_SECTION_PV1,
    SENEC_SECTION_PWR_UNIT,
    SENEC_SECTION_TEMPMEASURE,
    SENEC_SECTION_WALLBOX
)

DOMAIN: Final = "senec"
MANUFACTURE: Final = "SENEC GmbH"
SYSTYPE_SENECV4: Final = "systype_senecv4"
SYSTYPE_WEBAPI: Final = "systype_webapi"
SYSTYPE_SENECV3: Final = "systype_senecv3"
SYSTYPE_SENECV2: Final = "systype_senecv2"
SYSTYPE_INVERTV3: Final = "systype_invertv3"
SYSTEM_TYPES: Final = [SYSTYPE_SENECV3, SYSTYPE_SENECV4, SYSTYPE_SENECV2, SYSTYPE_WEBAPI, SYSTYPE_INVERTV3]

# the display names of the 3 different implemented backend-types
SYSTYPE_NAME_SENEC = "SENEC Main-Unit"
SYSTYPE_NAME_INVERTER = "SENEC Inverter Module"
SYSTYPE_NAME_WEBAPI = "SENEC WebAPI"

MODE_WEB: Final = "mode_web"
MODE_LOCAL: Final = "mode_local"
SYSTEM_MODES: Final = [MODE_LOCAL, MODE_WEB]

SETUP_SYS_TYPE: Final = "stype"
SETUP_SYS_MODE: Final = "smode"

CONF_DEV_TYPE_INT: Final = "dtype_int"
CONF_USE_HTTPS: Final = "use_https"
CONF_SUPPORT_BDC: Final = "has_bdc_support"
CONF_DEV_MASTER_NUM: Final = "master_plant_number"

CONF_DEV_TYPE: Final = "dtype"
CONF_DEV_MODEL: Final = "dname"
CONF_DEV_SERIAL: Final = "dserial"
CONF_DEV_VERSION: Final = "version"

CONF_SYSTYPE_SENEC: Final = "senec"
CONF_SYSTYPE_SENEC_V2: Final = "senec_v2"
CONF_SYSTYPE_INVERTER: Final = "inverter"
CONF_SYSTYPE_WEB: Final = "web"

"""Default config for Senec."""
DEFAULT_SYSTEM = SYSTYPE_SENECV3
DEFAULT_MODE = MODE_LOCAL
DEFAULT_HOST = "Senec"
DEFAULT_HOST_INVERTER = "Inverter"
DEFAULT_USERNAME = "E-Mail"
DEFAULT_NAME = "senec"
DEFAULT_NAME_INVERTER = "Inverter"
DEFAULT_NAME_WEB = "senec_WEBAPI"
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_SCAN_INTERVAL_SENECV2 = 60
# 5 minutes... [do not spam mein-senec.de]
DEFAULT_SCAN_INTERVAL_WEB = 300
DEFAULT_SCAN_INTERVAL_WEB_SENECV4 = 60

QUERY_BMS_KEY = "query_bms_data"
QUERY_FANDATA_KEY = "query_fan_data"
QUERY_WALLBOX_KEY = "query_wallbox_data"
QUERY_SPARE_CAPACITY_KEY = "query_spare_capacity"

@dataclass
class ExtSensorEntityDescription(SensorEntityDescription):
    controls: list[str] | None = None
    senec_lala_section: str | None = None

@dataclass
class ExtBinarySensorEntityDescription(BinarySensorEntityDescription):
    icon_off: str | None = None
    senec_lala_section: str | None = None

"""Supported number implementations"""
WEB_NUMBER_SENYOR_TYPES = [
    NumberEntityDescription(
        entity_registry_enabled_default=False,
        key="spare_capacity",
        name="Spare Capacity",
        device_class = NumberDeviceClass.BATTERY,
        mode = NumberMode.SLIDER,
        native_max_value = 50,
        native_min_value = 0,
        native_step = 1,
        native_unit_of_measurement = PERCENTAGE,
        icon="mdi:battery-lock",
    ),
]

"""Supported main unit switch types."""
MAIN_SWITCH_TYPES = [
    SwitchEntityDescription(
        key="safe_charge",
        name="Load Battery",
        icon="mdi:battery-charging-high",
    ),
    SwitchEntityDescription(
        entity_registry_enabled_default=False,
        key="li_storage_mode",
        name="Lithium Storage Mode - PV OFF",
        icon="mdi:solar-power",
    ),
]

"""Supported main unit binary_sensor types."""
MAIN_BIN_SENSOR_TYPES = [
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_l1_used",
        name="Wallbox L1 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_l2_used",
        name="Wallbox L2 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_l3_used",
        name="Wallbox L3 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_l1_used",
        name="Wallbox II L1 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_l2_used",
        name="Wallbox II L2 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_l3_used",
        name="Wallbox II L3 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_l1_used",
        name="Wallbox III L1 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_l2_used",
        name="Wallbox III L2 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_l3_used",
        name="Wallbox III L3 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_l1_used",
        name="Wallbox IV L1 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_l2_used",
        name="Wallbox IV L2 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_l3_used",
        name="Wallbox IV L3 used",
        icon="mdi:car-electric",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),

    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_FAN_SPEED,
        key="fan_inv_lv",
        name="Fan LV-Inverter",
        icon="mdi:fan",
        icon_off="mdi:fan-off",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        senec_lala_section=SENEC_SECTION_FAN_SPEED,
        entity_registry_enabled_default=False,
        key="fan_inv_hv",
        name="Fan HV-Inverter",
        icon="mdi:fan",
        icon_off="mdi:fan-off",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
]

WEB_SENSOR_TYPES = [

    SensorEntityDescription(
        key="consumption_total",
        name="House consumed",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="powergenerated_total",
        name="Solar generated",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="accuimport_total",
        name="Battery discharged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="accuexport_total",
        name="Battery charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="gridimport_total",
        name="Grid Imported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="gridexport_total",
        name="Grid Exported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),

    # accuimport_today
    # accuexport_today
    # gridimport_today
    # gridexport_today
    # powergenerated_today
    # consumption_today

    SensorEntityDescription(
        key="powergenerated_now",
        name="Solar Generated Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="consumption_now",
        name="House Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="accuimport_now",
        name="Battery Discharge Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="accuexport_now",
        name="Battery Charge Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="acculevel_now",
        name="Battery Charge Percent",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:home-battery",
        # device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="gridimport_now",
        name="Grid Imported Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="gridexport_now",
        name="Grid Exported Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    )
]

"""Supported main unit sensor types."""
MAIN_SENSOR_TYPES = [
    ExtSensorEntityDescription(
        key="system_state",
        name="System State",
        icon="mdi:solar-power",
    ),
    ExtSensorEntityDescription(
        key="battery_temp",
        name="Battery Temperature",
        native_unit_of_measurement=TEMP_CELSIUS,
        icon="mdi:thermometer",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        key="case_temp",
        name="Case Temperature",
        native_unit_of_measurement=TEMP_CELSIUS,
        icon="mdi:thermometer",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        key="mcu_temp",
        name="Controller Temperature",
        native_unit_of_measurement=TEMP_CELSIUS,
        icon="mdi:thermometer",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        key="solar_generated_power",
        name="Solar Generated Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="house_power",
        name="House Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_state_power",
        name="Battery State Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_state_current",
        name="Battery State Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_state_voltage",
        name="Battery State Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_charge_power",
        name="Battery Charge Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_discharge_power",
        name="Battery Discharge Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_charge_percent",
        name="Battery Charge Percent",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:home-battery",
        # device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="grid_state_power",
        name="Grid State Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="grid_imported_power",
        name="Grid Imported Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="grid_exported_power",
        name="Grid Exported Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="house_total_consumption",
        controls=("require_stats_fields"),
        name="House consumed",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="solar_total_generated",
        controls=("require_stats_fields"),
        name="Solar generated",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="battery_total_charged",
        controls=("require_stats_fields"),
        name="Battery charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="battery_total_discharged",
        controls=("require_stats_fields"),
        name="Battery discharged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="grid_total_import",
        controls=("require_stats_fields"),
        name="Grid Imported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="grid_total_export",
        controls=("require_stats_fields"),
        name="Grid Exported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp1_potential",
        name="MPP1 Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp1_current",
        name="MPP1 Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp1_power",
        name="MPP1 Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp2_potential",
        name="MPP2 Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp2_current",
        name="MPP2 Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp2_power",
        name="MPP2 Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp3_potential",
        name="MPP3 Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp3_current",
        name="MPP3 Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp3_power",
        name="MPP3 Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_freq",
        name="Enfluri Net Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_power_total",
        name="Enfluri Net Total Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_potential_p1",
        name="Enfluri Net Voltage Phase 1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_potential_p2",
        name="Enfluri Net Voltage Phase 2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_potential_p3",
        name="Enfluri Net Voltage Phase 3",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_current_p1",
        name="Enfluri Net Current Phase 1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_current_p2",
        name="Enfluri Net Current Phase 2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_current_p3",
        name="Enfluri Net Current Phase 3",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_power_p1",
        name="Enfluri Net Power Phase 1",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_power_p2",
        name="Enfluri Net Power Phase 2",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_power_p3",
        name="Enfluri Net Power Phase 3",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_freq",
        name="Enfluri Usage Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_power_total",
        name="Enfluri Usage Total Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_potential_p1",
        name="Enfluri Usage Voltage Phase 1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_potential_p2",
        name="Enfluri Usage Voltage Phase 2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_potential_p3",
        name="Enfluri Usage Voltage Phase 3",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_current_p1",
        name="Enfluri Usage Current Phase 1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_current_p2",
        name="Enfluri Usage Current Phase 2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_current_p3",
        name="Enfluri Usage Current Phase 3",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_power_p1",
        name="Enfluri Usage Power Phase 1",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_power_p2",
        name="Enfluri Usage Power Phase 2",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_power_p3",
        name="Enfluri Usage Power Phase 3",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_a1",
        name="Module A: Cell Temperature A1",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_a2",
        name="Module A: Cell Temperature A2",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_a3",
        name="Module A: Cell Temperature A3",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_a4",
        name="Module A: Cell Temperature A4",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_a5",
        name="Module A: Cell Temperature A5",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_a6",
        name="Module A: Cell Temperature A6",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_b1",
        name="Module B: Cell Temperature B1",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_b2",
        name="Module B: Cell Temperature B2",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_b3",
        name="Module B: Cell Temperature B3",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_b4",
        name="Module B: Cell Temperature B4",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_b5",
        name="Module B: Cell Temperature B5",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_b6",
        name="Module B: Cell Temperature B6",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_c1",
        name="Module C: Cell Temperature C1",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_c2",
        name="Module C: Cell Temperature C2",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_c3",
        name="Module C: Cell Temperature C3",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_c4",
        name="Module C: Cell Temperature C4",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_c5",
        name="Module C: Cell Temperature C5",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_c6",
        name="Module C: Cell Temperature C6",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_d1",
        name="Module D: Cell Temperature D1",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_d2",
        name="Module D: Cell Temperature D2",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_d3",
        name="Module D: Cell Temperature D3",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_d4",
        name="Module D: Cell Temperature D4",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_d5",
        name="Module D: Cell Temperature D5",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_temp_d6",
        name="Module D: Cell Temperature D6",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a1",
        name="Module A: Cell Voltage A1",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a2",
        name="Module A: Cell Voltage A2",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a3",
        name="Module A: Cell Voltage A3",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a4",
        name="Module A: Cell Voltage A4",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a5",
        name="Module A: Cell Voltage A5",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a6",
        name="Module A: Cell Voltage A6",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a7",
        name="Module A: Cell Voltage A7",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a8",
        name="Module A: Cell Voltage A8",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a9",
        name="Module A: Cell Voltage A9",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a10",
        name="Module A: Cell Voltage A10",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a11",
        name="Module A: Cell Voltage A11",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a12",
        name="Module A: Cell Voltage A12",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a13",
        name="Module A: Cell Voltage A13",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_a14",
        name="Module A: Cell Voltage A14",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b1",
        name="Module B: Cell Voltage B1",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b2",
        name="Module B: Cell Voltage B2",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b3",
        name="Module B: Cell Voltage B3",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b4",
        name="Module B: Cell Voltage B4",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b5",
        name="Module B: Cell Voltage B5",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b6",
        name="Module B: Cell Voltage B6",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b7",
        name="Module B: Cell Voltage B7",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b8",
        name="Module B: Cell Voltage B8",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b9",
        name="Module B: Cell Voltage B9",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b10",
        name="Module B: Cell Voltage B10",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b11",
        name="Module B: Cell Voltage B11",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b12",
        name="Module B: Cell Voltage B12",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b13",
        name="Module B: Cell Voltage B13",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_b14",
        name="Module B: Cell Voltage B14",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c1",
        name="Module C: Cell Voltage C1",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c2",
        name="Module C: Cell Voltage C2",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c3",
        name="Module C: Cell Voltage C3",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c4",
        name="Module C: Cell Voltage C4",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c5",
        name="Module C: Cell Voltage C5",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c6",
        name="Module C: Cell Voltage C6",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c7",
        name="Module C: Cell Voltage C7",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c8",
        name="Module C: Cell Voltage C8",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c9",
        name="Module C: Cell Voltage C9",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c10",
        name="Module C: Cell Voltage C10",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c11",
        name="Module C: Cell Voltage C11",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c12",
        name="Module C: Cell Voltage C12",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c13",
        name="Module C: Cell Voltage C13",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_c14",
        name="Module C: Cell Voltage C14",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d1",
        name="Module D: Cell Voltage D1",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d2",
        name="Module D: Cell Voltage D2",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d3",
        name="Module D: Cell Voltage D3",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d4",
        name="Module D: Cell Voltage D4",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d5",
        name="Module D: Cell Voltage D5",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d6",
        name="Module D: Cell Voltage D6",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d7",
        name="Module D: Cell Voltage D7",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d8",
        name="Module D: Cell Voltage D8",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d9",
        name="Module D: Cell Voltage D9",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d10",
        name="Module D: Cell Voltage D10",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d11",
        name="Module D: Cell Voltage D11",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d12",
        name="Module D: Cell Voltage D12",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d13",
        name="Module D: Cell Voltage D13",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cell_volt_d14",
        name="Module D: Cell Voltage D14",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_voltage_a",
        name="Module A: Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_voltage_b",
        name="Module B: Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_voltage_c",
        name="Module C: Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_voltage_d",
        name="Module D: Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_current_a",
        name="Module A: Current",
        icon="mdi:current-dc",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_current_b",
        name="Module B: Current",
        icon="mdi:current-dc",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_current_c",
        name="Module C: Current",
        icon="mdi:current-dc",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_current_d",
        name="Module D: Current",
        icon="mdi:current-dc",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_soc_a",
        name="Module A: State of charge",
        icon="mdi:battery-charging-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_soc_b",
        name="Module B: State of charge",
        icon="mdi:battery-charging-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_soc_c",
        name="Module C: State of charge",
        icon="mdi:battery-charging-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        key="bms_soc_d",
        name="Module D: State of charge",
        icon="mdi:battery-charging-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_soh_a",
        name="Module A: State of Health",
        icon="mdi:battery-heart-variant",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_soh_b",
        name="Module B: State of Health",
        icon="mdi:battery-heart-variant",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_soh_c",
        name="Module C: State of Health",
        icon="mdi:battery-heart-variant",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_soh_d",
        name="Module D: State of Health",
        icon="mdi:battery-heart-variant",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cycles_a",
        name="Module A: Cycles",
        icon="mdi:battery-sync",
        suggested_display_precision=0,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cycles_b",
        name="Module B: Cycles",
        icon="mdi:battery-sync",
        suggested_display_precision=0,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cycles_c",
        name="Module C: Cycles",
        icon="mdi:battery-sync",
        suggested_display_precision=0,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_BMS,
        entity_registry_enabled_default=False,
        key="bms_cycles_d",
        name="Module D: Cycles",
        icon="mdi:battery-sync",
        suggested_display_precision=0,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),

    # wallbox stuff
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_power",
        name="Wallbox Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:car-arrow-left",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_ev_connected",
        name="Wallbox EV Connected",
        icon="mdi:car-electric",
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        controls=("require_stats_fields"),
        key="wallbox_energy",
        name="Wallbox charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:ev-station",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_l1_charging_current",
        name="Wallbox L1 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_l2_charging_current",
        name="Wallbox L2 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_l3_charging_current",
        name="Wallbox L3 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_min_charging_current",
        name="Wallbox MIN charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_set_icmax",
        name="Wallbox set ICMAX",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_power",
        name="Wallbox II Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:car-arrow-left",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_ev_connected",
        name="Wallbox II EV Connected",
        icon="mdi:car-electric",
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        controls=("require_stats_fields"),
        key="wallbox_2_energy",
        name="Wallbox II charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:ev-station",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_l1_charging_current",
        name="Wallbox II L1 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_l2_charging_current",
        name="Wallbox II L2 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_l3_charging_current",
        name="Wallbox II L3 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_min_charging_current",
        name="Wallbox II MIN charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_2_set_icmax",
        name="Wallbox II set ICMAX",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_power",
        name="Wallbox III Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:car-arrow-left",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_ev_connected",
        name="Wallbox III EV Connected",
        icon="mdi:car-electric",
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        controls=("require_stats_fields"),
        key="wallbox_3_energy",
        name="Wallbox III charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:ev-station",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_l1_charging_current",
        name="Wallbox III L1 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_l2_charging_current",
        name="Wallbox III L2 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_l3_charging_current",
        name="Wallbox III L3 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_min_charging_current",
        name="Wallbox III MIN charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_3_set_icmax",
        name="Wallbox III set ICMAX",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_power",
        name="Wallbox VI Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:car-arrow-left",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_ev_connected",
        name="Wallbox IV EV Connected",
        icon="mdi:car-electric",
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        controls=("require_stats_fields"),
        key="wallbox_4_energy",
        name="Wallbox IV charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:ev-station",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_l1_charging_current",
        name="Wallbox IV L1 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_l2_charging_current",
        name="Wallbox IV L2 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_l3_charging_current",
        name="Wallbox IV L3 charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_min_charging_current",
        name="Wallbox IV MIN charging Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        senec_lala_section=SENEC_SECTION_WALLBOX,
        entity_registry_enabled_default=False,
        key="wallbox_4_set_icmax",
        name="Wallbox IV set ICMAX",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
]

INVERTER_SENSOR_TYPES = [
    ExtSensorEntityDescription(
        key="ac_voltage",
        name="AC Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="ac_current",
        name="AC Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="ac_power",
        name="AC Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="ac_power_fast",
        name="AC Power (fast)",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="ac_frequency",
        name="AC Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_bat_voltage",
        name="BDC Battery Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_bat_current",
        name="BDC Battery Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_bat_power",
        name="BDC Battery Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:battery-charging-100",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_link_voltage",
        name="BDC Link Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_link_current",
        name="BDC Link Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_link_power",
        name="BDC Link Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:power-plug-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="dc_voltage1",
        name="DC Voltage 1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="dc_voltage2",
        name="DC Voltage 2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="dc_current1",
        name="DC Current 1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="dc_current2",
        name="DC Current 2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="gridpower",
        name="Grid Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="gridconsumedpower",
        name="Grid consumed Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="gridinjectedpower",
        name="Grid injected Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="ownconsumedpower",
        name="Own consumed Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="derating",
        name="Derating",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:arrow-down-thin-circle-outline",
        state_class=SensorStateClass.MEASUREMENT,
    ),
]
