"""Constants for the Senec integration."""
from typing import Final
from dataclasses import dataclass

from homeassistant.components.binary_sensor import BinarySensorEntityDescription
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.components.switch import SwitchEntityDescription
from homeassistant.components.number import (
    NumberEntityDescription,
    NumberDeviceClass
)
from homeassistant.const import (
    ENERGY_KILO_WATT_HOUR,
    PERCENTAGE,
    POWER_WATT,
    POWER_KILO_WATT,
    TEMP_CELSIUS,
    UnitOfElectricPotential,
    UnitOfElectricCurrent, UnitOfFrequency,
)
from homeassistant.helpers.entity import EntityCategory

DOMAIN: Final = "senec"
MANUFACTURE: Final = "SENEC GmbH"
SYSTYPE_SENECV4: Final = "systype_senecv4"
SYSTYPE_WEBAPI: Final = "systype_webapi"
SYSTYPE_SENECV3: Final = "systype_senecv3"
SYSTYPE_SENECV2: Final = "systype_senecv2"
SYSTYPE_INVERTV3: Final = "systype_invertv3"
SYSTEM_TYPES: Final = [SYSTYPE_SENECV3, SYSTYPE_SENECV4, SYSTYPE_SENECV2, SYSTYPE_WEBAPI, SYSTYPE_INVERTV3]

MODE_WEB: Final = "mode_web"
MODE_LOCAL: Final = "mode_local"
SYSTEM_MODES: Final = [MODE_LOCAL, MODE_WEB]

SETUP_SYS_TYPE: Final = "stype"
SETUP_SYS_MODE: Final = "smode"

CONF_DEV_TYPE: Final = "dtype"
CONF_DEV_TYPE_INT: Final = "dtype_int"
CONF_USE_HTTPS: Final = "use_https"
CONF_SUPPORT_BDC: Final = "has_bdc_support"
CONF_DEV_NAME: Final = "dname"
CONF_DEV_SERIAL: Final = "dserial"
CONF_DEV_VERSION: Final = "version"
CONF_DEV_MASTER_NUM: Final = "master_plant_number"

CONF_SYSTYPE_SENEC: Final = "senec"
CONF_SYSTYPE_SENEC_V2: Final = "senec_v2"
CONF_SYSTYPE_INVERTER: Final = "inverter"
CONF_SYSTYPE_WEB: Final = "web"

"""Default config for Senec."""
DEFAULT_SYSTEM = SYSTYPE_SENECV3
DEFAULT_MODE = MODE_LOCAL
DEFAULT_HOST = "Senec"
DEFAULT_HOST_INVERTER = "Inverter"
DEFAULT_USERNAME = "E-Mail"
DEFAULT_NAME = "senec"
DEFAULT_NAME_INVERTER = "Inverter"
DEFAULT_NAME_WEB = "senec_WEBAPI"
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_SCAN_INTERVAL_SENECV2 = 60
# 5 minutes... [do not spam mein-senec.de]
DEFAULT_SCAN_INTERVAL_WEB = 300
DEFAULT_SCAN_INTERVAL_WEB_SENECV4 = 60


@dataclass
class ExtSensorEntityDescription(SensorEntityDescription):
    controls: list[str] | None = None


@dataclass
class ExtBinarySensorEntityDescription(BinarySensorEntityDescription):
    icon_off: str | None = None

"""Supported number implementations"""
WEB_NUMBER_SENYOR_TYPES = [
    NumberEntityDescription(
        entity_registry_enabled_default=False,
        key="spare_capacity",
        name="Spare Capacity",
        device_class = NumberDeviceClass.BATTERY,
        mode = "slider",
        native_max_value = 100,
        native_min_value = 0,
        native_step = 1,
        native_unit_of_measurement = PERCENTAGE,
        icon="mdi:battery-lock",
    ),
]

"""Supported main unit switch types."""
MAIN_SWITCH_TYPES = [
    SwitchEntityDescription(
        key="safe_charge",
        name="Load Battery",
        icon="mdi:battery-charging-high",
    ),
    SwitchEntityDescription(
        entity_registry_enabled_default=False,
        key="li_storage_mode",
        name="Lithium Storage Mode - PV OFF",
        icon="mdi:solar-power",
    ),
]

"""Supported main unit binary_sensor types."""
MAIN_BIN_SENSOR_TYPES = [
    ExtBinarySensorEntityDescription(
        key="fan_inv_lv",
        name="Fan LV-Inverter",
        icon="mdi:fan",
        icon_off="mdi:fan-off",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtBinarySensorEntityDescription(
        entity_registry_enabled_default=False,
        key="fan_inv_hv",
        name="Fan HV-Inverter",
        icon="mdi:fan",
        icon_off="mdi:fan-off",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
]

WEB_SENSOR_TYPES = [

    SensorEntityDescription(
        key="consumption_total",
        name="House consumed",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="powergenerated_total",
        name="Solar generated",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="accuimport_total",
        name="Battery discharged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="accuexport_total",
        name="Battery charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="gridimport_total",
        name="Grid Imported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="gridexport_total",
        name="Grid Exported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),

    # accuimport_today
    # accuexport_today
    # gridimport_today
    # gridexport_today
    # powergenerated_today
    # consumption_today

    SensorEntityDescription(
        key="powergenerated_now",
        name="Solar Generated Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="consumption_now",
        name="House Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="accuimport_now",
        name="Battery Discharge Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="accuexport_now",
        name="Battery Charge Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="acculevel_now",
        name="Battery Charge Percent",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:home-battery",
        # device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="gridimport_now",
        name="Grid Imported Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="gridexport_now",
        name="Grid Exported Power",
        native_unit_of_measurement=POWER_KILO_WATT,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.POWER,
        suggested_display_precision=3,
        state_class=SensorStateClass.MEASUREMENT,
    )
]

"""Supported main unit sensor types."""
MAIN_SENSOR_TYPES = [
    ExtSensorEntityDescription(
        key="system_state",
        name="System State",
        icon="mdi:solar-power",
    ),
    ExtSensorEntityDescription(
        key="battery_temp",
        name="Battery Temperature",
        native_unit_of_measurement=TEMP_CELSIUS,
        icon="mdi:thermometer",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        key="case_temp",
        name="Case Temperature",
        native_unit_of_measurement=TEMP_CELSIUS,
        icon="mdi:thermometer",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        key="mcu_temp",
        name="Controller Temperature",
        native_unit_of_measurement=TEMP_CELSIUS,
        icon="mdi:thermometer",
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        key="solar_generated_power",
        name="Solar Generated Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="house_power",
        name="House Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_state_power",
        name="Battery State Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_charge_power",
        name="Battery Charge Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_discharge_power",
        name="Battery Discharge Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="battery_charge_percent",
        name="Battery Charge Percent",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:home-battery",
        # device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="grid_state_power",
        name="Grid State Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="grid_imported_power",
        name="Grid Imported Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="grid_exported_power",
        name="Grid Exported Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="house_total_consumption",
        controls=("require_stats_fields"),
        name="House consumed",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="solar_total_generated",
        controls=("require_stats_fields"),
        name="Solar generated",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="battery_total_charged",
        controls=("require_stats_fields"),
        name="Battery charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="battery_total_discharged",
        controls=("require_stats_fields"),
        name="Battery discharged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="grid_total_import",
        controls=("require_stats_fields"),
        name="Grid Imported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="grid_total_export",
        controls=("require_stats_fields"),
        name="Grid Exported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp1_potential",
        name="MPP1 Potential",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp1_current",
        name="MPP1 Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp1_power",
        name="MPP1 Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp2_potential",
        name="MPP2 Potential",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp2_current",
        name="MPP2 Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp2_power",
        name="MPP2 Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp3_potential",
        name="MPP3 Potential",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp3_current",
        name="MPP3 Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="solar_mpp3_power",
        name="MPP3 Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_freq",
        name="Enfluri Net Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_power_total",
        name="Enfluri Net Total Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_potential_p1",
        name="Enfluri Net Potential Phase 1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_potential_p2",
        name="Enfluri Net Potential Phase 2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_potential_p3",
        name="Enfluri Net Potential Phase 3",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_current_p1",
        name="Enfluri Net Current Phase 1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_current_p2",
        name="Enfluri Net Current Phase 2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_current_p3",
        name="Enfluri Net Current Phase 3",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_power_p1",
        name="Enfluri Net Power Phase 1",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_power_p2",
        name="Enfluri Net Power Phase 2",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="enfluri_net_power_p3",
        name="Enfluri Net Power Phase 3",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_freq",
        name="Enfluri Usage Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_power_total",
        name="Enfluri Usage Total Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_potential_p1",
        name="Enfluri Usage Potential Phase 1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_potential_p2",
        name="Enfluri Usage Potential Phase 2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_potential_p3",
        name="Enfluri Usage Potential Phase 3",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_current_p1",
        name="Enfluri Usage Current Phase 1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_current_p2",
        name="Enfluri Usage Current Phase 2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_current_p3",
        name="Enfluri Usage Current Phase 3",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_power_p1",
        name="Enfluri Usage Power Phase 1",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_power_p2",
        name="Enfluri Usage Power Phase 2",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="enfluri_usage_power_p3",
        name="Enfluri Usage Power Phase 3",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_A1",
        name="Module A: Cell Temperature A1",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_A2",
        name="Module A: Cell Temperature A2",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_A3",
        name="Module A: Cell Temperature A3",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_A4",
        name="Module A: Cell Temperature A4",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_A5",
        name="Module A: Cell Temperature A5",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_A6",
        name="Module A: Cell Temperature A6",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_B1",
        name="Module B: Cell Temperature B1",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_B2",
        name="Module B: Cell Temperature B2",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_B3",
        name="Module B: Cell Temperature B3",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_B4",
        name="Module B: Cell Temperature B4",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_B5",
        name="Module B: Cell Temperature B5",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_B6",
        name="Module B: Cell Temperature B6",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_C1",
        name="Module C: Cell Temperature C1",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_C2",
        name="Module C: Cell Temperature C2",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_C3",
        name="Module C: Cell Temperature C3",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_C4",
        name="Module C: Cell Temperature C4",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_C5",
        name="Module C: Cell Temperature C5",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_C6",
        name="Module C: Cell Temperature C6",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_D1",
        name="Module D: Cell Temperature D1",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_D2",
        name="Module D: Cell Temperature D2",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_D3",
        name="Module D: Cell Temperature D3",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_D4",
        name="Module D: Cell Temperature D4",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_D5",
        name="Module D: Cell Temperature D5",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_temp_D6",
        name="Module D: Cell Temperature D6",
        icon="mdi:thermometer",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
        entity_category=EntityCategory.DIAGNOSTIC,
    ),

    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A1",
        name="Module A: Cell Voltage A1",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A2",
        name="Module A: Cell Voltage A2",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A3",
        name="Module A: Cell Voltage A3",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A4",
        name="Module A: Cell Voltage A4",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A5",
        name="Module A: Cell Voltage A5",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A6",
        name="Module A: Cell Voltage A6",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A7",
        name="Module A: Cell Voltage A7",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A8",
        name="Module A: Cell Voltage A8",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A9",
        name="Module A: Cell Voltage A9",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A10",
        name="Module A: Cell Voltage A10",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A11",
        name="Module A: Cell Voltage A11",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A12",
        name="Module A: Cell Voltage A12",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A13",
        name="Module A: Cell Voltage A13",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_A14",
        name="Module A: Cell Voltage A14",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B1",
        name="Module B: Cell Voltage B1",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B2",
        name="Module B: Cell Voltage B2",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B3",
        name="Module B: Cell Voltage B3",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B4",
        name="Module B: Cell Voltage B4",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B5",
        name="Module B: Cell Voltage B5",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B6",
        name="Module B: Cell Voltage B6",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B7",
        name="Module B: Cell Voltage B7",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B8",
        name="Module B: Cell Voltage B8",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B9",
        name="Module B: Cell Voltage B9",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B10",
        name="Module B: Cell Voltage B10",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B11",
        name="Module B: Cell Voltage B11",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B12",
        name="Module B: Cell Voltage B12",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B13",
        name="Module B: Cell Voltage B13",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_B14",
        name="Module B: Cell Voltage B14",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C1",
        name="Module C: Cell Voltage C1",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C2",
        name="Module C: Cell Voltage C2",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C3",
        name="Module C: Cell Voltage C3",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C4",
        name="Module C: Cell Voltage C4",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C5",
        name="Module C: Cell Voltage C5",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C6",
        name="Module C: Cell Voltage C6",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C7",
        name="Module C: Cell Voltage C7",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C8",
        name="Module C: Cell Voltage C8",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C9",
        name="Module C: Cell Voltage C9",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C10",
        name="Module C: Cell Voltage C10",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C11",
        name="Module C: Cell Voltage C11",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C12",
        name="Module C: Cell Voltage C12",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C13",
        name="Module C: Cell Voltage C13",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_C14",
        name="Module C: Cell Voltage C14",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D1",
        name="Module D: Cell Voltage D1",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D2",
        name="Module D: Cell Voltage D2",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D3",
        name="Module D: Cell Voltage D3",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D4",
        name="Module D: Cell Voltage D4",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D5",
        name="Module D: Cell Voltage D5",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D6",
        name="Module D: Cell Voltage D6",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D7",
        name="Module D: Cell Voltage D7",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D8",
        name="Module D: Cell Voltage D8",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D9",
        name="Module D: Cell Voltage D9",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D10",
        name="Module D: Cell Voltage D10",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D11",
        name="Module D: Cell Voltage D11",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D12",
        name="Module D: Cell Voltage D12",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D13",
        name="Module D: Cell Voltage D13",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="bms_cell_volt_D14",
        name="Module D: Cell Voltage D14",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="bms_voltage_A",
        name="Module A: Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_voltage_B",
        name="Module B: Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_voltage_C",
        name="Module C: Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_voltage_D",
        name="Module D: Voltage",
        icon="mdi:lightning-bolt",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="bms_current_A",
        name="Module A: Current",
        icon="mdi:current-dc",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_current_B",
        name="Module B: Current",
        icon="mdi:current-dc",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_current_C",
        name="Module C: Current",
        icon="mdi:current-dc",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_current_D",
        name="Module D: Current",
        icon="mdi:current-dc",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="bms_soc_A",
        name="Module A: State of charge",
        icon="mdi:battery-charging-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_soc_B",
        name="Module B: State of charge",
        icon="mdi:battery-charging-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_soc_C",
        name="Module C: State of charge",
        icon="mdi:battery-charging-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_soc_D",
        name="Module D: State of charge",
        icon="mdi:battery-charging-high",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="bms_soh_A",
        name="Module A: State of Health",
        icon="mdi:battery-heart-variant",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_soh_B",
        name="Module B: State of Health",
        icon="mdi:battery-heart-variant",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_soh_C",
        name="Module C: State of Health",
        icon="mdi:battery-heart-variant",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="bms_soh_D",
        name="Module D: State of Health",
        icon="mdi:battery-heart-variant",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="bms_cycles_A",
        name="Module A: Cycles",
        icon="mdi:battery-sync",
        suggested_display_precision=0,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="bms_cycles_B",
        name="Module B: Cycles",
        icon="mdi:battery-sync",
        suggested_display_precision=0,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="bms_cycles_C",
        name="Module C: Cycles",
        icon="mdi:battery-sync",
        suggested_display_precision=0,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    ExtSensorEntityDescription(
        key="bms_cycles_D",
        name="Module D: Cycles",
        icon="mdi:battery-sync",
        suggested_display_precision=0,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),

    # wallbox stuff
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="wallbox_power",
        name="Wallbox Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:car-arrow-left",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="wallbox_ev_connected",
        name="Wallbox EV Connected",
        icon="mdi:car-electric",
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        controls=("require_stats_fields"),
        key="wallbox_energy",
        name="Wallbox charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:ev-station",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
]

INVERTER_SENSOR_TYPES = [
    ExtSensorEntityDescription(
        key="ac_voltage",
        name="AC Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="ac_current",
        name="AC current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-ac",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="ac_power",
        name="AC Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="ac_power_fast",
        name="AC Power (fast)",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="ac_frequency",
        name="AC Frequency",
        native_unit_of_measurement=UnitOfFrequency.HERTZ,
        icon="mdi:meter-electric",
        device_class=SensorDeviceClass.FREQUENCY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_bat_voltage",
        name="BDC Battery Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_bat_current",
        name="BDC Battery Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_bat_power",
        name="BDC Battery Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:battery-charging-100",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_link_voltage",
        name="BDC Link Voltage",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_link_current",
        name="BDC Link Current",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        controls=("bdc_only"),
        key="bdc_link_power",
        name="BDC Link Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:power-plug-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        key="dc_voltage1",
        name="DC Voltage 1",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="dc_voltage2",
        name="DC Voltage 2",
        native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        icon="mdi:lightning-bolt",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="dc_current1",
        name="DC current 1",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="dc_current2",
        name="DC current 2",
        native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        icon="mdi:current-dc",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.MEASUREMENT,
    ),

    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="gridpower",
        name="Grid Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="gridconsumedpower",
        name="Grid consumed Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="gridinjectedpower",
        name="Grid injected Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        entity_registry_enabled_default=False,
        key="ownconsumedpower",
        name="Own consumed Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    ExtSensorEntityDescription(
        key="derating",
        name="Derating",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:arrow-down-thin-circle-outline",
        state_class=SensorStateClass.MEASUREMENT,
    ),
]
